[project]
name = "streamlit-cropper"
version = "0.2.2"
authors = [{name="Turner Anderson", email="andersontur11@gmail.com"}]
description = "A simple image cropper for Streamlit"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "streamlit >= 1.27.0",
    "Pillow >= 9.2.0",
    "numpy >= 1.23.5"
]

[project.urls]
"Homepage" = "https://github.com/turner-anderson/streamlit-cropper"
"Bug Tracker" = "https://github.com/turner-anderson/streamlit-cropper/issues"

[build-system]
requires = ["setuptools>=61.0",
            "streamlit >= 1.27.0",
            "Pillow >= 9.2.0",
            "numpy >= 1.23.5"
]
build-backend = "setuptools.build_meta"